## Function to load and compare objects saved as RDS
## Can be modified to work with RDA as well. Will need to read in objects differently, will need to provide object

## !! Check the tolerance threshold set on line 18 !! ##

# provide paths to rds files
compare_obj <- function(ca_path, cr_path){
  
# generate a list of files to compare based on what was generated by CR  
obj_outs <- list.files(cr_path, pattern = ".rds")

# recursively load and compare objects
for (i in obj_outs) {
  if (file.exists(paste0(cr_path, "/",i))) {
    cat("\n", i, "\n", "\n")
    tmp_CR <- readRDS(paste0(cr_path, "/", i))
    tmp_CA <- readRDS(paste0(ca_path, "/", i))
    print(waldo::compare(tmp_CR, tmp_CA, tolerance = 1e-4))
    cat("\n", "\n", "\n")
 } else {
   cat("\n", i, "\n", "\n")
   # or report that there is not a file
   print(paste0(i, " is not found in independent run output directory "))
   cat("\n", "\n", "\n")
  }
} 
}

