## Function to load and compare delimited text
## User needs to provide paths to directories, the delimiter for the files, and the pattern of the file ending
## !! Check the tolerance threshold set on line 18 !! ##

compare_delim <- function(ca_path, cr_path, delim = NULL, patt){
  # generate a list of files to compare based on what was generated by CR  
delim_outs <- list.files(cr_path, pattern = patt)

# recursively load and compare delimited output
for (i in delim_outs) {
  if (file.exists(paste0(cr_path, "/",i))) {
    cat("\n", i, "\n", "\n")
    tmp_CR <- readr::read_delim(paste0(cr_path, "/", i), delim = delim, col_names = FALSE)
    tmp_CA <- readr::read_delim(paste0(ca_path, "/", i), delim = delim, col_names = FALSE)
    print(waldo::compare(tmp_CR, tmp_CA, tolerance = 1e-4))
    cat("\n", "\n", "\n")
 } else {
   cat("\n", i, "\n", "\n")
   # or report that there is not a file
   print(paste0(i, " is not found in independent run output directory "))
   cat("\n", "\n", "\n")
  }
} 
}
