## Function to load and stage images side by side for visual comparison

# provide paths to img files and the type of image to look for
compare_figure <- function(ca_path, cr_path, patt){

# generate a list of imgs to compare based on what was generated by CR
fig_outs <- list.files(cr_path, pattern = patt)

# recursively load and stage imgs side-by-side for comparison
for (i in fig_outs) {
  if (file.exists(paste0(cr_path, "/",i))) {
    cat("\n", i,"\n", "\n")
    plots <- lapply(c(paste0(cr_path, "/",i),
                      paste0(cr_path, "/",i)), 
                      function(x) {
    return(grid::rasterGrob(png::readPNG(x)))
  })
  print(gridExtra::grid.arrange(gridExtra::arrangeGrob(grobs = plots, ncol = 2)))
  cat("\n", "\n", "\n")
 } else {
   cat("\n", i,"\n", "\n")
   print(paste0(i, " is not found in independent run output directory"))
   cat("\n", "\n", "\n")
  }
 }
}
